language: ruby

rvm:
  - 2.0.0
  - jruby-19mode
  - rbx-19mode

notifications:
  email: false

before_install:
  - gem install bundler

before_script:
  - ln -s config/database.yml.example config/database.yml
  - bundle exec rake db:migrate
  - bundle exec secret:replace

script:
  - bundle exec rake test
