language: ruby

rvm:
  - 2.3
  - jruby

matrix:
  allow_failures:
    - rvm: jruby

notifications:
  email: false

sudo: false

services:
  - elasticsearch

before_install:
  - bundle config github.https true
  - gem install bundler

before_script:
  - ln -s database.yml.example config/database.yml
  - bundle exec rake secret:replace
  - bundle exec rake db:migrate

script:
  - bundle exec rake test
