host: moeil.orgizm.net

default_domain: orgizm.net
default_quota: 5242880

minimal_password_length: 8

blocked_usernames:
  - dummy

elasticsearch: true

spam_alias_username_length: 6

mx_check_domain: mx.orgizm.net

dirty_rails4_warden_workaround: true
